<a href="https://colab.research.google.com/github/xesmaze/cpsc541-fall2024/blob/main/Lab_4/Lab_4_Extra_Credit.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Extra Credit Exercise: Multiple Regression with Matrix Operations

This exercise will guide you through performing multiple regression using matrix operations. Some parts of the code have been left incomplete for you to fill in.

## Problem Setup

You have three predictors (X1, X2, X3) and one response variable (Y). Your goal is to fit a linear model of the form:

$$
Y = \beta_0 + \beta_1 X_1 + \beta_2 X_2 + \beta_3 X_3 + \epsilon
$$

Using the normal equation:

$$
\mathbf{\beta} = (\mathbf{X}^\top \mathbf{X})^{-1} \mathbf{X}^\top \mathbf{Y}
$$

## Step 1: Define Data
We will simulate a small dataset with 5 observations for two predictors (X1, X2) and the response variable (Y).



# Instructions
## Fill in the blanks in the code below to complete the steps.

## Step 1: Define Data
## We will use the following simulated data with 5 observations:

X1 = [2,4,6,8,10,12,14]
X2 = [3,7,2,9,5,13,6]
X3 = [1,4,8,6,2,11,9]
Y = [20,30,25,45,40,50,60]

In [ ]:
import numpy as np

# Simulated data for two predictors (X1, X2) and one response (Y)
# Fill in the missing code below
X1 = np.array([___])  # Fill in the data for X1
X2 = np.array([___])  # Fill in the data for X2
Y = np.array([___])   # Fill in the data for Y

# Display the data
print("X1:", X1)
print("X2:", X2)
print("Y:", Y)

X1: [ 2  4  6  8 10]
X2: [1 3 5 7 9]
X3: [5 3 4 2 1]
Y: [15 25 35 45 55]


#Step 2: Construct the Design Matrix

In [ ]:
# Construct the design matrix X (with an intercept column of ones)
# X = [1, X1, X2, X3]
X = np.column_stack((___, X1, X2, X3))  # Fill in the missing code

# Display the design matrix
print("Design Matrix (X):")
print(X)


Design Matrix (A):
[[ 1. 12.  6.]
 [ 1. 14.  8.]
 [ 1. 16. 10.]
 [ 1. 18. 12.]
 [ 1. 20. 14.]]


#Step 3: Solve the Normal Equation

In [ ]:
# Compute the normal equation: beta = (X^T X)^(-1) X^T Y

# Compute X^T X
X_transpose_X = np.dot(___, ___)  # Fill in the missing code

# Compute (X^T X)^(-1)
X_transpose_X_inv = np.linalg.inv(X_transpose_X)

# Compute X^T Y
X_transpose_Y = np.dot(___, ___)  # Fill in the missing code

# Calculate beta (the coefficients)
beta = np.dot(X_transpose_X_inv, X_transpose_Y)

# Display the coefficients
print("Coefficients (Intercept, beta_1, beta_2, beta_3):", beta)

Coefficients (Intercept, beta_1, beta_2, beta_3): [-3.50000000e+01  5.00000000e+00  1.33448808e-12]


#Step 4: Predict the Response Values

In [ ]:
# Use the coefficients to predict Y
Y_pred = np.dot(___, ___)  # Fill in the missing code

print("Predicted Y:", Y_pred)
print("Actual Y:", Y)

Predicted Y: [15. 25. 35. 45. 55.]
Actual Y: [15 25 35 45 55]


#Step 5: Calculate Residuals
Calculate the residuals between the actual and predicted values.

In [ ]:
# Calculate the residuals (errors)
residuals = ___  # Fill in the missing code
print("Residuals (errors):", residuals)

Residuals (errors): [1.57029945e-11 1.65378822e-11 1.60440550e-11 1.68682845e-11
 1.63637992e-11]
